- name: deleting record "{{ name }}"
  hosts: all
  tasks:
    - dnsimple:
        account_email: "{{ email }}"
        account_api_token: "{{ token }}"
        domain: "{{ domain }}"
        record: "{{ name }}"
        type: "{{ type }}"
        value: "{{ ip }}"
        state: absent
      delegate_to: localhost
      register: record